@startuml


left to right direction

:Директор: as Man1
:Складовщик: as Man2
:Продавец: as Man3
:Кассир: as Man4


package Магазин {
    rectangle Управление {
        (Посмотреть отчёты) as UC1.1
        (Заказать товар) as UC1.2
    }

    rectangle Склад {
        (Создать отчёт по складу) as UC2.1
        (Проверить товары) as UC2.2
        (Принять товар) as UC2.3

        UC2.1 ..> UC2.2 : include
    }

    rectangle "Торговый зал" {
        (Выписать накладную) as UC3.1
    }

    rectangle Касса {
        (Выписать чек) as UC4.1
        (Принять деньги) as UC4.2
        (Оформить возврат) as UC4.3

        (Выдать товар) as UC0.1
        (Забрать товар) as UC0.2
        (Вернуть деньги) as UC0.3

        UC4.1 ..> UC4.2 : include

        UC4.1 ..> UC0.1 : include
        UC4.3 ..>UC0.2 : include
        UC4.3 ..> UC0.3 : include
    }

    Man1 -- UC1.1
    Man1 -- UC1.2

    Man2 -- UC2.1
    Man2 -- UC2.2
    Man2 -- UC2.3

    Man3 -- UC3.1

    Man4 -- UC4.1
    Man4 -- UC4.2
    Man4 -- UC4.3

    Man3 <|-- Man4


    UC1.1 ..> UC2.1 : extend
    UC1.2 ..> UC2.1 : include

    UC3.1 ..> UC2.2 : include

    UC4.1 ..> UC3.1 : extend

    UC0.1 ..> UC2.2 : extend
    UC0.2 ..> UC2.3 : extend
}


@enduml
