@startuml

|Накладная|
|Чек|
|Склад|



|Накладная|
start
repeat
    if (Товар есть в наличии?) then (Да)
        :Добавить товар;
    endif
repeat while (Не все товары добавлены)
if (Цена не устраивает?) then (Да)
else
    |Чек|
    :Сформировать чек;
    :Получить деньги;

    |Склад|
    repeat
        :Выдать товар;
    repeat while (Не все товары выданы)
    |Накладная|
endif

stop


@enduml